---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  tags:
    - nginx
    - packages

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
  tags:
    - nginx
    - config

- name: Create Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ app_name }}
  notify: restart nginx
  tags:
    - nginx
    - config

- name: Enable Nginx configuration
  file:
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/{{ app_name }}
    state: link
  notify: restart nginx
  tags:
    - nginx
    - config

- name: Start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  tags:
    - nginx
    - service