---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  tags:
    - nginx
    - packages

- name: Remove default Nginx configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
  tags:
    - nginx
    - config

- name: Create Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ nginx_app_name }}
    mode: "0644"
  notify: restart nginx
  tags:
    - nginx
    - config

- name: Enable Nginx configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ nginx_app_name }}
    dest: /etc/nginx/sites-enabled/{{ nginx_app_name }}
    state: link
  notify: restart nginx
  tags:
    - nginx
    - config

- name: Start and enable Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
  tags:
    - nginx
    - service
