---
- name: Create application directory
  ansible.builtin.file:
    path: "{{ webapp_app_dir }}"
    state: directory
    owner: "{{ webapp_app_user }}"
    group: "{{ webapp_app_user }}"
    mode: "0755"
  tags:
    - webapp
    - directory

- name: Copy application files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ webapp_app_dir }}/{{ item }}"
    owner: "{{ webapp_app_user }}"
    group: "{{ webapp_app_user }}"
    mode: "0644"
  loop:
    - app.js
    - package.json
  notify: restart webapp
  tags:
    - webapp
    - deploy

- name: Install Node.js dependencies
  community.general.npm:
    path: "{{ webapp_app_dir }}"
    production: true
  become: true
  become_user: "{{ webapp_app_user }}"
  tags:
    - webapp
    - dependencies

- name: Create PM2 ecosystem file
  ansible.builtin.template:
    src: ecosystem.config.js.j2
    dest: "{{ webapp_app_dir }}/ecosystem.config.js"
    owner: "{{ webapp_app_user }}"
    group: "{{ webapp_app_user }}"
    mode: "0644"
  notify: restart webapp
  tags:
    - webapp
    - config

- name: Create application environment file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ webapp_app_dir }}/.env"
    owner: "{{ webapp_app_user }}"
    group: "{{ webapp_app_user }}"
    mode: "0600"
  notify: restart webapp
  tags:
    - webapp
    - config

- name: Start application with PM2
  become: true
  become_user: "{{ webapp_app_user }}"
  ansible.builtin.shell: |
    cd {{ webapp_app_dir }}
    pm2 delete {{ webapp_app_name }} || true
    pm2 start ecosystem.config.js
    pm2 save
  environment:
    NODE_OPTIONS: "--max-old-space-size={{ webapp_max_old_space_size }}"
  changed_when: true
  tags:
    - webapp
    - service

- name: Setup PM2 startup script
  ansible.builtin.shell: |
    env PATH=$PATH:/usr/bin pm2 startup systemd -u {{ webapp_app_user }} --hp /home/{{ webapp_app_user }}
    systemctl enable pm2-{{ webapp_app_user }}
  changed_when: true
  tags:
    - webapp
    - startup
