---
- name: Download NodeJS setup script
  ansible.builtin.get_url:
    url: "https://deb.nodesource.com/setup_{{ nodejs_version }}.x"
    dest: /tmp/nodejs_setup.sh
    mode: '0755'
  tags:
    - nodejs
    - setup

- name: Run NodeJS setup script
  ansible.builtin.command: /tmp/nodejs_setup.sh
  args:
    creates: /etc/apt/sources.list.d/nodesource.list
  tags:
    - nodejs
    - setup

- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: present
    update_cache: true
  tags:
    - nodejs
    - packages

- name: Install PM2 globally
  community.general.npm:
    name: pm2
    global: true
    state: present
  tags:
    - nodejs
    - pm2

- name: Create application directory
  ansible.builtin.file:
    path: "{{ nodejs_app_dir }}"
    state: directory
    owner: "{{ common_app_user }}"
    group: "{{ common_app_user }}"
    mode: '0755'
  tags:
    - nodejs
    - app
