---
galaxy_info:
  author: keith
  description: Node.js and PM2 installation for application servers
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
dependencies:
  - role: common


