---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags:
    - common
    - apt

- name: Install essential packages
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - git
      - htop
      - vim
      - unzip
    state: present
  tags:
    - common
    - packages

- name: Configure swap
  notify: restart swap
  tags:
    - common
    - swap
  block:
    - name: Stop swap
      ansible.builtin.command: /usr/sbin/dphys-swapfile swapoff
      failed_when: false
      changed_when: false

    - name: Set swap size
      ansible.builtin.lineinfile:
        path: /etc/dphys-swapfile
        regexp: '^CONF_SWAPSIZE='
        line: 'CONF_SWAPSIZE=1024'

    - name: Setup and start swap
      ansible.builtin.shell: |
        /usr/sbin/dphys-swapfile setup
        /usr/sbin/dphys-swapfile swapon
      failed_when: false
      changed_when: false

- name: Set timezone
  community.general.timezone:
    name: Asia/Manila
  tags:
    - common
    - timezone

- name: Create application user
  ansible.builtin.user:
    name: "{{ common_app_user }}"
    shell: /bin/bash
    groups: sudo
    append: true
  tags:
    - common
    - users
