---
- name: Configure all Raspberry Pi servers
  hosts: all
  become: true
  roles:
    - common

- name: Setup database server
  hosts: database_servers
  become: true
  roles:
    - database

- name: Setup web servers
  hosts: web_servers
  become: true
  roles:
    - nodejs
    - webapp

- name: Setup load balancer
  hosts: load_balancers
  become: true
  roles:
    - nginx
    - angular
