---
- name: Validate cluster deployment
  hosts: all
  gather_facts: true
  tasks:
    - name: Check system uptime
      ansible.builtin.command: uptime
      register: uptime_result
      changed_when: false
      
    - name: Display uptime
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: {{ uptime_result.stdout }}"

- name: Validate web servers
  hosts: web_servers
  tasks:
    - name: Check if Node.js is installed
      ansible.builtin.command: node --version
      register: node_version
      changed_when: false
      
    - name: Display Node.js version
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: Node.js {{ node_version.stdout }}"

- name: Validate database server
  hosts: database_servers
  tasks:
    - name: Check MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started
      check_mode: true

- name: Validate load balancer
  hosts: load_balancers
  tasks:
    - name: Check nginx service
      ansible.builtin.service:
        name: nginx
        state: started
      check_mode: true
